inherit_from: "./rspec.yml"

require:
  - jets/rubocop
  - rubocop-rails
  - rubocop-performance
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Style/FrozenStringLiteralComment:
  Enabled: true

Standard/SemanticBlocks:
  Enabled: false

Lint/UselessAssignment:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Rails/Output:
  Enabled: true
  Exclude:
    - 'lib/tasks/**/*'

Gemspec/OrderedDependencies:
  Enabled: true
